// Do not use this file while building or linking with Silikego.
// Instead, use the file generated by CMake.

// Put silikego/silikego/include-ide in your IDE's include search list
// so that this file resolves as Silikego/Api.h to eliminate errors from
// missing the header file Silikego/Api.h.

#define SILIKEGOCORE_EXPORT
#define SILIKEGOCORE_NO_EXPORT
#define SILIKEGOCORE_DEPRECATED
#define SILIKEGOCORE_DEPRECATED_EXPORT
#define SILIKEGOCORE_DEPRECATED_NO_EXPORT
#define SILIKOEGCORE_NO_DEPRECATED
