// Do not use this file while building or linking with Silikego.
// Instead, use the file generated by CMake.

// Put silikego/silikego/include-ide in your IDE's include search list
// so that this file resolves as Silikego/Api.h to eliminate errors from
// missing the header file Silikego/Api.h.

#define SILIKEGO_EXPORT
#define SILIKEGO_NO_EXPORT
#define SILIKEGO_DEPRECATED
#define SILIKEGO_DEPRECATED_EXPORT
#define SILIKEGO_DEPRECATED_NO_EXPORT
#define SILIKOEG_NO_DEPRECATED
